[env:esp32s3-custom-marauder]
board = esp32s3
framework = arduino
board_build.partitions = default_8MB.csv
board_build.flash_mode = qio

build_flags =
    -D ESP32S3
    -D ST7735_DRIVER=1
    -D ST7735_GREENTAB160=1
    -D TFT_RGB_ORDER=TFT_BGR
    -D TFT_WIDTH=128
    -D TFT_HEIGHT=160
    
    ; --- توصيلات الشاشة (ST7735 TFT) على ESP32-S3 ---
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_MISO=-1
    -D TFT_CS=10
    -D TFT_DC=9
    -D TFT_RST=14
    -D TFT_BL=21
    -D TFT_BACKLIGHT_ON=HIGH

    ; --- توصيلات الـ Joystick (5-Way) ---
    -D JOY_UP=1
    -D JOY_DOWN=2
    -D JOY_LEFT=3
    -D JOY_RIGHT=4
    -D JOY_ENTER=5

    -D USER_SETUP_LOADED=1
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=27000000
    -D DEVICE_NAME='"Bruce-ESP32S3-Custom"'

lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.9
    bodmer/TFT_eSPI @ ^2.5.31
